export const simplePrepositions = [
    "about",
    "above",
    "across",
    "after",
    "against",
    "along",
    "amid",
    "among",
    "around",
    "as",
    "at",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "besides",
    "between",
    "beyond",
    "but",
    "by",
    "concerning",
    "considering",
    "despite",
    "down",
    "during",
    "except",
    "excluding",
    "following",
    "for",
    "from",
    "in",
    "inside",
    "into",
    "like",
    "minus",
    "near",
    "of",
    "off",
    "on",
    "onto",
    "opposite",
    "out",
    "outside",
    "over",
    "past",
    "per",
    "plus",
    "regarding",
    "round",
    "save",
    "since",
    "than",
    "through",
    "throughout",
    "till",
    "to",
    "toward",
    "towards",
    "under",
    "underneath",
    "unlike",
    "until",
    "up",
    "upon",
    "versus",
    "via",
    "with",
    "within",
    "without"
];

export const compoundPrepositions = [
    "according to",
    "ahead of",
    "apart from",
    "as for",
    "as of",
    "as per",
    "as to",
    "aside from",
    "because of",
    "close to",
    "due to",
    "except for",
    "far from",
    "inside of",
    "instead of",
    "near to",
    "next to",
    "on to",
    "out of",
    "outside of",
    "owing to",
    "prior to",
    "pursuant to",
    "such as",
    "thanks to",
    "up to"
];

export const phrasalPrepositions = [
    "as far as",
    "as well as",
    "by means of",
    "in accordance with",
    "in addition to",
    "in case of",
    "in front of",
    "in lieu of",
    "in place of",
    "in spite of",
    "on account of",
    "on behalf of",
    "with regard to",
    "with respect to"
];
